\ *************************************
\ define AT commands for ESP32 GSM
\    Filename:      ATcommands.fs
\    Date:          29 jan 2026
\    Updated:       31 jan 2026
\    File Version:  1.0
\    MCU:           ESP32-S3 - ESP32 WROOM
\    Forth:         ESP32forth all versions 7.0.7.+
\    Copyright:     Marc PETREMANN
\    Author:        Marc PETREMANN
\    GNU General Public License
\ **************************************


RECORDFILE /spiffs/ATcommands.fs

\ GSM_RX and GSM_TX defined in serialGSM.fs file

\ initialize GSM_TX buffer
: AT$! ( -- )
    s" AT" GSM_TX $!
  ;

\ append string to GSM_TX buffer
: ATappend$ ( addr len -- )
    GSM_TX append$
  ;

\ append number  to GSM_TX buffer
: ATappendNum ( n -- )
    base @ >r  decimal
    <# #s #> GSM_TX append$
    r> base !
  ;

-1 value DISPLAY_GSM_TX     \ control conditionnal display for GSM_TX buffer
 0 value SEND_GSM_TX        \ control conditionnal display for GSM_TX buffer

\ display and|or send GSM_TX buffer 
: .GsmTxBuffer ( -- )
    DISPLAY_GSM_TX if   \ conditionnal display
        cr GSM_TX type
    then
    SEND_GSM_TX if      \ conditionnal sending
        GSM_TX serialWrite
    then
  ;

include /spiffs/BASEcommands.fs
include /spiffs/SMScommands.fs

cr ." ATcommands.fs loaded"
<EOF>


Command Description
A/      RE-ISSUES THE LAST COMMAND GIVEN
ATA     ANSWER AN INCOMING CALL
ATD     MOBILE ORIGINATED CALL TO DIAL A NUMBER
ATD><N> ORIGINATE CALL TO PHONE NUMBER IN CURRENT MEMORY
ATD><STR> ORIGINATE CALL TO PHONE NUMBER IN MEMORY WHICH CORRESPONDS TO FIELD <STR>
ATDL    REDIAL LAST TELEPHONE NUMBER USED
ATE     SET COMMAND ECHO MODE
ATH     DISCONNECT EXISTING CONNECTION
ATI     DISPLAY PRODUCT IDENTIFICATION INFORMATION
ATL     SET MONITOR SPEAKER LOUDNESS
ATM     SET MONITOR SPEAKER MODE
+++     SWITCH FROM DATA MODE OR PPP ONLINE MODE TO COMMAND MODE
ATO     SWITCH FROM COMMAND MODE TO DATA MODE
ATP     SELECT PULSE DIALLING
ATQ     SET RESULT CODE PRESENTATION MODE
ATS0    SET NUMBER OF RINGS BEFORE AUTOMATICALLY ANSWERING THE CALL
ATS3    SET COMMAND LINE TERMINATION CHARACTER
ATS4    SET RESPONSE FORMATTING CHARACTER
ATS5    SET COMMAND LINE EDITING CHARACTER
ATS6    PAUSE BEFORE BLIND DIALLING
ATS7    SET NUMBER OF SECONDS TO WAIT FOR CONNECTION COMPLETION
ATS8    SET NUMBER OF SECONDS TO WAIT FOR COMMA DIAL MODIFIER ENCOUNTERED IN DIAL STRING OF D COMMAND
ATS10   SET DISCONNECT DELAY AFTER INDICATING THE ABSENCE OF DATA CARRIER
ATT     SELECT TONE DIALING
ATV     TA RESPONSE FORMAT
ATX     SET CONNECT RESULT CODE FORMAT AND MONITOR CALL
ATZ     RESET DEFAULT CONFIGURATION
AT&C    SET DCD FUNCTION MODE
AT&D    SET DTR FUNCTION MODE
AT&F    FACTORY DEFINED CONFIGURATION
AT&V    DISPLAY CURRENT CONFIGURATION
AT&W    STORE ACTIVE PROFILE
AT+GCAP REQUEST COMPLETE TA CAPABILITIES LIST
AT+GMI  REQUEST MANUFACTURER IDENTIFICATION
AT+GMM  REQUEST TA MODEL IDENTIFICATION
AT+GMR  REQUEST TA REVISION IDENTIFICATION OF SOFTWARE RELEASE
AT+GOI  REQUEST GLOBAL OBJECT IDENTIFICATION
AT+GSN  REQUEST TA SERIAL NUMBER IDENTIFICATION (IMEI)
AT+ICF  SET TE-TA CONTROL CHARACTER FRAMING
AT+IFC  SET TE-TA LOCAL DATA FLOW CONTROL
AT+IPR  SET TE-TA FIXED LOCAL RATE
AT+HVOIC DISCONNECT VOICE CALL ONLY





